import random

dictionaries = [
    {"required": "обов’язковий",
    "even": "навіть",
    "influence": "вплив",
    "another": "інший, але невідомо який",
    "involved": "залучений",
    "fostered by": "сприяв",
    "consequences": "наслідки",
    "certain": "певний",
    "ever": "коли-небудь",
    "efforts": "зусилля",
    "somehow": "якось",
    "frighten": "лякати",
    "purpose": "мета",
    "avoid": "уникати",
    "besides": "окрім того",
    "decide": "вирішувати",
    "probably": "ймовірно",
    "suddenly": "раптово",
    "major": "основний",
    "boast of": "хвалитися",
    "research": "дослідження",
    "offer": "пропозиція",
    "citizens": "громадяни",
    "restored": "відновлений",
    "landmark": "пам'ятка (орієнтир)",
    "liberated": "звільнений",
    "participant": "учасник",
    "over the past": "за останні (роки/місяці)",
    "revitalized": "відроджений",
    "peaceful": "мирний",
    "completely": "повністю",
    "I’m looking forward to it": "Я з нетерпінням чекаю на це",
    "I didn’t catch that": "Я не зрозумів це",
    "How’s it going?": "Як справи?",
    "That’s enough": "Цього достатньо",
    "It’s worth it": "Це того варте",
    "As far as I know": "Наскільки я знаю",
    "consider": "розглядати",
    "introduce": "представити",
    "first of all": "передусім",
    "hair pins": "шпильки для волосся",
    "gems": "коштовності",
    "dream will come true": "мрія здійсниться",
    "copper wire": "мідний дріт",
    "useful": "корисний",
    "inspires": "надихає",
    "among": "серед",
    "to be a step away from": "бути за крок до",
    "injured": "поранений",
    "recover": "одужувати",
    "then": "потім",
    "above": "вище",
    "to draw inspiration from": "черпати натхнення з",
    "distinct": "чіткий",
    "creative activity": "творча діяльність",
    "overcome": "подолати",
    "hardship": "труднощі",
    "achieve a goal": "досягти поставленої мети",
    "worthy": "гідний",
    "carpenter":"столяр",
    "proud": "гордий",
    "it can't be said": "не можна сказати",
    "residential areas": "житлові райони",
    "average": "звичайний",
    "factory": "завод",
    "quiet person": "тиха людина",
    "he looks like": "він схожий на",
    "good-mannered": "вихований",
    "close-knit": "дружний",
    "initially": "спочатку",
    "explain": "пояснити",
    "including": "включаючи",
    "compare": "порівнювати",
    "currently": "наразі",
    "features": "функції",
    "by character": "характером",
    "moved in": "вселитися",
    "down from st": "нижче по вулиці",
    "jealous of": "заздрити",
    "until": "поки",
    "fallen out": "посваритися",
    "to tell the truth": "по правді кажучи",
    "shared": "поділяти",
    "rather" : "краще б, охочіше"},

    {"despite" : "незважаючи на",
    "talks me into": "вмовляє мене",
    "various": "різні",
    "appeals to": "приваблює",
    "inquisitive" : "допитливий",
    "honest and direct": "чесна й відверта",
    "rely" : "покладатись",
    "giving": "безкорисливий",
    "i will go out of my way": "я докладу зусиль",
    "reserved": "стриманий",
    "friendship": "дружба",
    "treasured" : "цінний",
    "to run into problems": "зіткнутися з проблемами",
    "I'm not an exception": "я не виняток",
    "indulge": "балувати",
    "I'm addicted to": "я залежний від",
    "exciting": "захопливий",
    "carry": "нести ноутбук",
    "advance": "просуватися",
    "strange": "дивний",
    "escape": "втекти",
    "imagine": "уявляти",
    "wear": "носити одяг",
    "fried": "жарені",
    "definitely": "безумовно",
    "therefore": "тому",
    "essential": "суттєвий",
    "unforgettable": "незабутній",
    "sights": "пам'ятки",
    "multistoried-building": "багатоповерхівка",
    "premises": "приміщення",
    "spacious": "просторий",
    "heating": "опалення",
    "set": "набір",
    "sofa": "диван",
    "cozy": "затишний",
    "carpets": "килими",
    "keeps": "тримає",
    "plates": "тарілки",
    "dishes": "посуд",
    "serves": "обслуговує",
    "dwelling": "житло",
    "over": "над",
    "attitudes": "ставлення",
    "determine": "визначати",
    "behavior": "поведінка",
    "meaningful": "значущий",
    "raise": "піднімати",
    "moreover": "більше того",
    "create bonds": "створювати зв'язок",
    "belong": "належати",
    "strengthen": "зміцнювати",
    "complicate": "ускладнювати",
    "ensure": "забезпечити",
    "occasions": "події",
    "ancient": "давній",
    "particular": "конкретний",
    "such": "такий",
    "responsible": "відповідальний",
    "maintain": "підтримати",
    "values": "цінності"},

    {"farm": "ферма",
    "hunt": "полювання",
    "protect": "захищати",
    "property": "власність",
    "whether": "чи",
    "lizard": "ящірка",
    "lack": "нестача",
    "neglected": "занедбаний",
    "via": "через",
    "provide": "забезпечувати",
    "disabilities": "інвалідність",
    "beneficial": "корисний",
    "lowers": "знижує",
    "pressure": "тиск",
    "relieves stress": "знімає стрес",
    "decrease": "зменшувати",
    "diseases": "хвороби",
    "shape": "форма",
    "owing": "унаслідок",
    "although": "хоча",
    "to make a comparison": "робити порівняння",
    "care": "догляд",
    "prevent": "запобігати",
    "polluted": "забруднений",
    "generally": "загалом",
    "prone": "схильний до чогось (негативного)",
    "slight ailments and serious diseases": "легкі захворювання та серйозні хвороби",
    "minor": "незначний",
    "coming down with": "починати хворіти",
    "flu": "грип",
    "increase": "збільшуватися",
    "common": "поширений",
    "to take a preventive measures": "приймати профілактичні заходи",
    "according to": "за даними когось..",
    "widespread": "широко поширений",
    "obesity": "ожиріння",
    "cancer": "рак",
    "unwilling": "неохочий",
    "tend": "мати схильність",
    "disregard": "ігнорувати",
    "poorly": "погано",
    "refuse": "відмовлятися",
    "appointment": "прийом (у лікаря)",
    "worse": "гірше",
    "approaches": "підходи",
    "cure": "лікування, вилікування",
    "kidney": "нирка",
    "approve": "одобрювати"},
    
    {"remind": "нагадувати",
    "improve": "покращувати",
    "overload": "перевантаження",
    "ownership": "власність",
    "boundaries": "межі",
    "advise": "радити",
    "notify": "повідомляти",
    "check": "перевіряти",
    "connected": "пов'язаний",
    "thus": "отже",
    "emerging": "новий",
    "necessary": "необхідний",
    "lean": "пісний (про їжу)",
    "grains": "зернові",
    "processed foods": "перероблені продукти",
    "contains": "містить",
    "habits": "звички",
    "harmful": "шкідливий",
    "wealth": "багатство",
    "accommodation": "житло",
    "extensive": "обширний",
    "attractions": "пам’ятки",
    "advantages": "переваги",
    "former": "колишній",
    "constant": "постійний",
    "anxiety": "тривога",
    "environs": "околиц",
    "desire": "бажання",
    "conductive": "сприятливий",
    "rural areas": "сільська місцевість",
    "less": "менше",
    "crowding": "натовп",
    "on the other hand": "з іншого боку",
    "far": "далеко",
    "source": "джерело",
    "certainly": "звісно",
    "dimensions": "розміри",
    "worth trying": "варто спробувати",
    "safe": "безпечний",
    "mankind": "людство",
    "aware": "обізнаний",
    "stroll": "прогулянка",
    "scale": "шкала",
    "agricultural": "сільськогосподарський",
    "while": "поки",
    "shelf": "полиця",
    "below": "нижче",
    "borrow": "позичати",
    "here we go": "поїхали",
    "spilled": "пролив(ся)",
    "pack": "пакувати",
    "bring": "принести",
    "chew": "жувати",
    "breath": "дихання",
    "smell": "запах",
    "neat": "акуратний",
    "gum": "жувальна гумка",
    "hand sanitizer": "антисептик для рук",
    "wipes": "серветки",
    "hairbrush": "гребінець",
    "in any case": "в будь якому випадку",
    "enough": "достатньо"},

    {"notates": "занотовує",
    "still": "все ще",
    "by the way": "до речі",
    "tolerance": "похибка",
    "urgent": "терміновий",
    "plant": "рослина",
    "attitude": "ставлення",
    "crowds": "натовпи",
    "customers": "клієнти",
    "cheaper": "дешевший",
    "blame": "звинувачувати",
    "behave": "поводитись",
    "guess": "здогадуватись",
    "measure": "міра",
    "chemicals": "хімікати",
    "hurt": "боліти",
    "cleanlines": "чистота",
    "nutrients": "поживні речовини",
    "appear": "виглядати як хтось",
    "weak": "слабкий",
    "route": "маршрут",
    "treat": "частувати",
    "valley": "долина",
    "signs": "знаки",
    "overestimate": "переоцінювати",
    "impact": "вплив",
    "pace": "темп",
    "defeat": "поразка",
    "threaten": "загрожувати",
    "ability": "здатність",
    "facilitate": "сприяти",
    "especially": "особливо",
    "stake": "частка",
    "caused": "спричинений",
    "promotion": "просування",
    "through": "через",
    "implement": "впроваджувати",
    "go past the cafe": "пройди повз кафе",
    "opposite the cafe": "навпроти кафе"
},

    {"garbage": "сміття",
    "strict": "суворий",
    "crops": "сільськогосподарські культури",
    "saint": "святий",
    "hail": "град",
    "stale": "черствий",
    "hold": "тримати",
    "resolve": "вирішувати",
    "attraction": "привабливість",
    "strength": "сила",
    "own": "власний",
    "waste": "відходи",
    "wild": "дикий",
    "core": "ядро",
    "gray": "сірий",
    "specification": "уточнення",
    "recent": "нещодавній",
    "curtain": "штора",
    "reliable": "надійний",
    "reproduce": "відтворювати",
    "familiarize": "ознайомитися",
    "grow": "рости",
    "detain": "затримувати",
    "annoy": "дратувати",
    "legacy": "спадщина",
    "for some reason": "з якоїсь причини",
    "bench": "лавка",
    "divide": "ділити",
    "perhaps": "можливо",
    "doubt": "сумнів",
    "kind of": "типу",
    "used to": "колись робив раніше",
    "be used to": "бути звиклим до",
    "I'll keep that in mind": "я матиму це на увазі",
    "affected": "уражений",
    "whatever": "що завгодно",
    "ubiquitous": "всюди сущий",
    "accountant": "бухгалтер",
    "plumber": "сантехнік",
    "surgeon": "хірург",
    "waiter": "офіціант",
    "loud": "гучний",
    "rarely": "рідко",
    "climb": "лізти",
    "convince": "переконувати"}
]

def get_word():
    words = list(dictionaries[4].items()) + list(dictionaries[5].items())
    random.shuffle(words)
    return words.pop()

def get_dictionary(bot, message):
    try:
        number = int(message.text) - 1
        if number < 0 or number >= len(dictionaries):
            bot.send_message(message.chat.id, "Dict not found")
            return

        selected_dict = dictionaries[number]
        text = "\n".join([f"{key} — {value}" for key, value in selected_dict.items()])
        bot.send_message(message.chat.id, text)
    except ValueError:
        bot.send_message(message.chat.id, "Please enter a valid number")